menkaiProject/accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
from django.contrib.auth import views as auth_views 

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビュー呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対し,
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/', views.SignUpView.as_view(), name='signup'),

    # サインアップ完了ページのビュー呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対し,
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),

    # ログインページの表示
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対し,
    # django.contrib.auth.views.LoginViewsをインスタンス化して
    # ログインページを表示する
    path('login/', 
        # ログイン用のテンプレート(フォーム)をレンダリング
        auth_views.LoginView.as_view(template_name='login.html'), name='login'
        ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対し,
    # django.contrib.auth.views.LogoutViewsをインスタンス化して
    # ログアウトさせる
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

]

menkaiProject/menkaiProject/urls.py
from django.contrib import admin
from django.urls import path, include # include追加
# auth.viewsをインポートしてauth_viewsという名前で利用する
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    # patientidCheck.urlsへのURLパターンを追加
    # path('',include('patientidCheck.urls')),

    # visit.urlsへのURLパターンを追加
    path('',include('visit.urls')),

    # accounts.urlsへのURLパターンを追加
    path('',include('accounts.urls')),

        
    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurl.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
            auth_views.PasswordResetView.as_view(
            template_name = "password_reset.html"),
            name = 'password_reset'),

    # メール送信完了ページ
    path('password_reset/done/',
            auth_views.PasswordResetDoneView.as_view(
            template_name = "password_reset_sent.html"),
            name = 'password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
            auth_views.PasswordResetConfirmView.as_view(
            template_name = "password_reset_form.html"),
            name = 'password_reset_confirm'),

    # パスワードリセット完了ページ
    path('reset/done/',
            auth_views.PasswordResetCompleteView.as_view(
            template_name = "password_reset_done.html"),
            name = 'password_reset_complete'),

]

menkaiProject/visit/urls.py
from django.urls import path
from . import views

# URLパターンを逆引きできるように名前を付ける
app_name = 'visit'

# URLパターンを登録するための変数

urlpatterns = [
    # visitアプリへのアクセスはviewsモジュールのIndexViewにリダイレクトする
    path('', views.IndexView.as_view(), name='index'),
    
    # visitアプリへのアクセスはviewsモジュールのCreateVisitViewにリダイレクトする
    path('regist_visit/', views.CreateVisitView.as_view(), name='regist_visit'), 

    # 登録完了ページへのアクセスはviewsモジュールのRegistSuccessViewを実行
    path('regist_visit_done/', views.RegistSuccessView.as_view(), name='regist_visit_done'),

    # 詳細ページ
    # visit_detail/<Visit registテーブルのid値>にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('visit_detail/<int:pk>',
        views.DetailView.as_view(),
        name = 'visit_detail'
    ),
   
    # マイページ
    # mypage/へのアクセスはMypageViewを実行
    path('mypage/', views.MypageView.as_view(), name='mypage'),

    # 登録情報の削除
    # visit/<Visit registテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    # pkはprimary_keyのこと
    path('visit/<int:pk>/delete/',
         views.Reception0DeleteView.as_view(),
         name='visit_delete'
    ),
]

menkaiProject/visit/models.py
from django.db import models
# accountsアプリのmodelsモジュールからCustomUserをインポート
from accounts.models import CustomUser
from django.utils import timezone
from django.core.validators import MinLengthValidator
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.validators import UnicodeUsernameValidator


class Reception0(models.Model):
    '''
    # 受付番号自動生成
    reception_id = models.CharField(
        verbose_name='受付番号', 
        primary_key=True,
        max_length=10,
        editable=False,
    )
    '''

    # CustomUserモデル(のuser_id)とReceptionモデルを
    # 1対多の関係で結び付ける
    # CustomUserが親でReceptionが子の関係となる
    user = models.ForeignKey(
        CustomUser,
        # フィールドのタイトル
        verbose_name='email',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )

    # 来院目的用のフィールド
    P_CHOICES = [
            ("患者様と面会", "患者様と面会"),
            ("荷物の受け渡しのみ", "荷物の受け渡しのみ"),
            ("医師と面談", "医師と面談"),
        ]
    purpose = models.CharField(
        verbose_name='来院目的', # フィールドのタイトル
        max_length=20,
        choices=P_CHOICES
        )
    
    # 同行者の有無boolean
    A_CHOICES = [(True,"はい"), (False,"いいえ")]
    accompany = models.BooleanField(
        verbose_name='同行者はいらっしゃいますか？',
        choices=A_CHOICES,
        default=True,
        )
    
     # 登録日時のフィールド
    visited_at = models.DateTimeField(
        verbose_name='登録日時', # フィールドのタイトル
        auto_now_add=True,      # 日時を自動追加
        blank=True,
        null=True
        )

    # 同行者用のモデル
    companion_last_name = models.CharField(verbose_name='同行者様の姓', max_length=100 , blank=True, null=True)
    companion_first_name = models.CharField(verbose_name='同行者様の名', max_length=100,  blank=True, null=True)

    # 続柄
    R2_CHOICES = [
        ("配偶者", "配偶者"),
        ("子", "子"),
        ("父・母", "父・母"),
        ("兄・弟・姉・妹", "兄・弟・姉・妹"),
        ("兄・弟・姉・妹の配偶者", "兄・弟・姉・妹の配偶者"),
        ("子の配偶者", "子の配偶者"),
        ("子の子", "子の子"),
        ("配偶者の兄・弟・姉・妹", "配偶者の兄・弟・姉・妹"),
        ("その他", "その他"),
    ]
    relationship2 = models.CharField(verbose_name='続柄', max_length=30, choices=R2_CHOICES, blank=True, null=True)
        
   

    class Meta:
        verbose_name ='0面会事前登録情報'
        verbose_name_plural = '0面会事前登録データベース'

    def get_id(self):
        #オブジェクトを文字列に変換して返す
        
        return self.user


class Reception1(models.Model):
    '''
    reception_id = models.OneToOneField(
        Reception0,
        # フィールドのタイトル
        verbose_name='.id',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )
    '''
    user = models.ForeignKey(
        CustomUser,
        # フィールドのタイトル
        verbose_name='email',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )

    # 体温
    bt1 = models.DecimalField(
        verbose_name='体温',
        max_digits=3,
        decimal_places=1,
        blank=True,
        null=True,
        default=36.0,
        validators=[MinValueValidator(34.0), MaxValueValidator(43.0)]
        )

    # 同行者体温    
    bt2 = models.DecimalField(
        verbose_name='体温',
        max_digits=3,
        decimal_places=1,
        blank=True,
        null=True,
        default=36.0,
        validators=[MinValueValidator(34.0), MaxValueValidator(43.0)]
        )

   
    # 来棟時間のフィールド
    InHospital = models.DateTimeField(
        verbose_name='来棟時間', # フィールドのタイトル
        default=None,
        blank=True,
        null=True
        )

    class Meta:
        verbose_name ='1面会時登録情報'
        verbose_name_plural = '1面会時登録データベース'

    def get_id(self):
        #オブジェクトを文字列に変換して返す
        
        return self.user



class Reception3(models.Model):
    '''
    r_id = models.OneToOneField(
        Reception0,
        # フィールドのタイトル
        verbose_name='id',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )
    '''
    user = models.ForeignKey(
        CustomUser,
        # フィールドのタイトル
        verbose_name='email',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )
    

    # 帰棟時間のフィールド
    OutHospital = models.DateTimeField(
        verbose_name='帰棟時間', # フィールドのタイトル
        default=None,
        blank=True,
        null=True
        )

    # 受付番号が有効か無効か
    active = models.BooleanField(
        verbose_name='面会番号が有効か無効か',
        default=True,
    )

    # 帰棟時間が入ると無効になる
    def save(self, *args, **kwargs):
        if self.OutHospital is None:
            self.active = True
        elif self.OutHospital is not None:
            self.active = False
        super(Reception3, self).save(*args, **kwargs)

    class Meta:
        verbose_name ='3帰院時刻情報'
        verbose_name_plural = '3帰院時刻データベース'
    
    def get_id(self):
        #オブジェクトを文字列に変換して返す
        
        return self.user

menkaiProject/visit/forms.py
from django import forms
from django.forms import ModelForm
from .models import Reception0

class Reception0Form(forms.ModelForm):
    
    class Meta:
        '''
        Attributes:
            model: モデルのクラス
            fields: フォームで使用するモデルのフィールド指定
        '''
        model = Reception0
        fields = {'purpose','accompany', 'companion_last_name', 'companion_first_name', 'relationship2'}

   

menkaiProject/visit/views.py
from django.shortcuts import render
# django.views.genericからTemplateView、ListViewをインポート
from django.views.generic import TemplateView, ListView
# django.views.genericからCreateViewをインポート
from django.views.generic import CreateView
# django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからReceptionFormをインポート
from .forms import Reception0Form
# method_decoratorをインポート
from django.utils.decorators import method_decorator
# login_requiredをインポート
from django.contrib.auth.decorators import login_required
# modelsモジュールからモデルReceptionをインポート
from .models import Reception0, Reception1
# django.views.genericからDetailViewをインポート
from django.views.generic import DetailView
# django.views.genericからDeleteViewをインポート
from django.views.generic import DeleteView

class IndexView(TemplateView):
    '''トップページのビュー
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # モデルBlogPostのオブジェクトにorder_by()を適用して
    # 投稿日時の降順で並べ替える
    queryset = Reception0.objects.order_by('-visited_at')
   

# デコレーターにより、CreateVisitViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')
class CreateVisitView(CreateView):
    '''来院ページのビュー
    
    VisitingFormで定義されているモデルとフィールドと連携して
    登録データをデータベースに登録する
    
    Attributes:
      form_class: モデルとフィールドが登録されたフォームクラス
      template_name: レンダリングするテンプレート
      success_url: データベスへの登録完了後のリダイレクト先
    '''
    # forms.pyのReception1Formをフォームクラスとして登録
    form_class = Reception0Form
    # レンダリングするテンプレート
    template_name = "regist_visit.html"
    # フォームデータ登録完了後のリダイレクト先
    success_url = reverse_lazy('visit:regist_visit_done')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う
        
        parameters:
          form(django.forms.Form):
            form_classに格納されているReceptionFormオブジェクト
        Return:
          HttpResponseRedirectオブジェクト:
            スーパークラスのform_valid()の戻り値を返すことで、
            success_urlで設定されているURLにリダイレクトさせる
        '''
        # commit=FalseにしてPOSTされたデータを取得
        regist_visitdata = form.save(commit=False)
        # 登録ユーザーのidを取得してモデルのuserフィールドに格納
        regist_visitdata.user = self.request.user
        # 登録データをデータベースに登録
        regist_visitdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)
        

    
class RegistSuccessView(TemplateView):
    '''投稿完了ページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
    '''
    # index.htmlをレンダリングする
    template_name ='regist_visit_success.html'


class DetailView(DetailView):

    # detail.htmlをレンダリングする
    template_name ='detail.html'
    # クラス変数modelにモデルを設定
    model = Reception0


class MypageView(ListView):
    '''マイページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    # mypage.htmlをレンダリングする
    template_name ='mypage.html'
    # クラス変数modelにモデルを設定
    model = Reception0

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''
      # 現在ログインしているユーザー名はHttpRequest.userに格納されている
      # filter(userフィールド=userオブジェクト)で絞り込む
      queryset = Reception0.objects.filter(
        user=self.request.user).order_by('-visited_at')
      # クエリによって取得されたレコードを返す
      return queryset

    def get_count(self):
      
      # self.kwargsでキーワードの辞書を取得し、
      # userキーの値(ユーザーテーブルのid)を取得
      #_id = self.kwargs['user']
      # filter(フィールド名=id)で絞り込む
      active_true = Reception0.objects.filter(
        active=True).count()
      # クエリによって取得されたレコードを返す
      return active_true

   
 
    
class Reception0DeleteView(DeleteView):
    '''レコードの削除を行うビュー
    
    Attributes:
      model: モデル
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
      success_url: 削除完了後のリダイレクト先のURL
    '''
    # 操作の対象はReception0モデル
    model = Reception0
    # mypage.htmlをレンダリングする
    template_name ='visit_delete.html'
    # 処理完了後にマイページにリダイレクト
    success_url = reverse_lazy('visit:mypage')

    def delete(self, request, *args, **kwargs):
      '''レコードの削除を行う
      
      Parameters:
        self: PhotoDeleteViewオブジェクト
        request: WSGIRequest(HttpRequest)オブジェクト
        args: 引数として渡される辞書(dict)
        kwargs: キーワード付きの辞書(dict)
                {'pk': 21}のようにレコードのidが渡される
      
      Returns:
        HttpResponseRedirect(success_url)を返して
        success_urlにリダイレクト
      '''
      # スーパークラスのdelete()を実行
      return super().delete(request, *args, **kwargs)
    

menkaiProject/visit/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja" class="h-100">
    <head>
        <titke></titke>
        <meta charset="utf-8">
        
        <!-- ビューポートの設定 -->
        <meta name="viewpoint" content="width=device-width,initial-scale=1">
        <!-- スタイルシートの読み込み -->
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'header-footer.css' %}" />
        
    </head>
  
  <body>
    <!-- ページのヘッダー -->
    <header>
      <!-- ナビゲーションバーのヘッダー -->
      
        <div class="navbar">
            <div>
              <!-- ヘッダーのタイトルと本文-->
              <strong>面会スマート</strong>
              <p>
                面会をされるご家族のみなさま、<br>
                ○○病院に入院されている患者様に面会をするにあたって、事前に本サイトからご登録お願いいたします。
              </p>
            </div>

            <div>
              <ul>
                <!-- ナビゲーションメニュー -->
                {% if user.is_authenticated %}
                  <!-- ログイン中のメニュー -->
                  <li><a href="{% url 'visit:mypage' %}"
                         class="text-white">マイページ</a></li>
                  <li><a href="{% url 'accounts:logout' %}"
                         class="text-white">ログアウト</a></li>
                  <li><a href="{% url 'password_reset' %}"
                         class="text-white">パスワードのリセット</a></li>
                {% else %}
                  <!-- ログイン状態ではない場合のメニュー -->
                  <li><a href="{% url 'accounts:signup' %}"
                         class="text-white">会員登録はこちら</a></li>
                  <li><a href="{% url 'accounts:login' %}"
                         class="text-white">ログイン</a></li>
                {% endif %}
              </ul>
            </div>
        </div>
    </header>
    
    
    <!-- メインコンテンツ -->
    <main>
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む -->
      {% block contents %}{% endblock %}
    </main>

    <!-- フッター -->
    <footer>
        <br>
        <br>
        <p>
          <a href="{% url 'visit:index' %}">トップページへ</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p>(c)2021 Eiko Takaoka Laboratory, Sophia Universuty. All Rights Reserved.</p>
    </footer>
    <!-- フッターの終了 -->
      

  </body>
</html>

menkaiProject/visit/templates/detail.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}登録情報詳細{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム, 条件分岐 -->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる -->
          <div class="col offset-3">
            <!-- 来院目的 -->
            <p>来院目的：{{object.purpose}}</p>
            <br>
            <!-- 同行者の有無 -->
            <p>同行者がいる：{{object.accompany}}</p>
            <br>
           <!-- 登録時間 -->
           <p>登録時間：{{object.visited_at}}</p>
           <br>
            
            <!-- 登録情報がログイン中のユーザーのものであれば削除ボタンを表示 -->
            {% if request.user == object.user %}
            <form method="POST">
            <!-- リンク先のURL
                 visit/<Visitingテーブルのid値>/delete/ -->
            <a href="{% url 'visit:visit_delete' object.pk %}"
               class="btn btn-primary my-2">削除する</a>
            {% endif %}
            
          </dv>
        </dv>
      </dv>
      {% endblock %}

menkaiProject/visit/templates/index.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}{% endblock %}

      {% block contents %}
      
      <!-- タイトルテンプレートの組み込み -->
      {% include "visit_title.html" %}

      <!-- 登録一覧テンプレートの組み込み -->
      {% include "visit_list.html" %}
      
      {% endblock %}

menkaiProject/visit/templates/mypage.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}マイページ{% endblock %}

      {% block contents %}
      
      <!-- タイトルテンプレートは組み込まない -->
      
      <!-- ユーザーの投稿件数を表示 -->
      {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
          <h4>{{user.last_name}} {{user.first_name}}さんのマイページ</h4>
          {% if object_list.count != 1 %}
            <p>{{user.last_name}} {{user.first_name}}さんが既に登録されている面会予定はありません</p>
            <a href="{% url 'visit:regist_visit' %}">面会事前登録をする</a>
          {% else %} 
          　<p>こちら↓から登録済みの面会の詳細が確認できます</p> 
          {% endif %}
            
         
          <!-- 登録一覧テンプレートの組み込み -->
          {% include "visit_list.html" %} 

      
        </div>
        <hr>
      {% endif %}
        
    
      {% endblock %}

menkaiProject/visit/templates/regist_visit.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}面会事前登録{% endblock %}
      {% block contents %}
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <div class="form1">         
            <form method="POST"
                  enctype="multipart/form-data">
                  {% csrf_token %}
                  <p>来院目的：{{ form.purpose }}</p>
                  <p>同伴者の有無：{{ form.accompany }}</p>
                  <br>
                  <p style="color: gray">※上記で「はい」を選択した方のみご入力ください。「いいえ」を選択した方は空欄のままご登録ください。</p>
                  <p>同伴者の姓：{{ form.companion_last_name }}</p> 
                  <p>同伴者の名：{{ form.companion_first_name }}</p>
                  <p>同伴者の患者様との続柄：{{ form.relationship2 }}</p>
                  <button type="submit" class="post_button">登録する</button>
            </form>
          </div> 
        </div>
      </div>
      {% endblock %}

menkaiProject/visit/templates/regist_visit_success.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}

<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}面会事前登録完了{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br><br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる -->
          <div class="col offset-2">
            <h4>面会事前登録が完了しました!</h4>  
          </dv>
        </dv>
      </dv>
      {% endblock %}

menkaiProject/visit/templates/visit_delete.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}{% endblock %}

      {% block contents %}
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる、ここも条件分岐？ -->
          
            <form method="POST">
             
              <p>削除してもよろしいですか?</p>
              {% csrf_token %}
              <button class="btn"
                      type="submit">削除</button>
              <a href="{% url 'visit:visit_detail' object.pk %}"
                 class="btn ">キャンセル</a>
            </form>
            <br>
        </div>
      </div>
      {% endblock %}

menkaiProject/visit/templates/visit_list.html
<div class="album py-5 bg-light">
      <div class="container">
        <!-- 行要素を配置 -->
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          <!--
           レコードが格納されたobject_listから
           レコードを1行ずつrecordに取り出す
          -->
          {% for record in object_list %}
              <!-- タイトルとボタンを出力するブロック -->
              <div class="card-body">
               
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <!-- 詳細ページを表示するボタン, active=false(無効)だと非表示,true(有効)だと表示 -->
                    <!-- リンク先のURL: photo-detail/<Photo postsテーブルのid値> -->
                    <button type="button"class="btn btn-sm btn-outline-secondary"onclick="location.href='{% url 'visit:visit_detail' record.pk %}'">
                            面会登録の詳細確認
                    </button>
                  </div>           
                </div>
          </div>
          <br>
          {% endfor %}
          <!-- forブロック終了 -->
        <!-- 行要素ここまで -->
        </div>
      </div>
</div>

menkaiProject/visit/templates/visit_title.html
<!-- タイトルとナビゲーションボタン -->
<section class="py-5 text-center container">
    <div class="row">
      <div class="col">
        <!-- タイトルと本文 -->
        <br>
        <p>
          <!-- ナビゲーションボタン -->
          {% if user.is_authenticated %}
            <!-- ログイン中のボタン -->
            <!-- 受付番号acive==False(無効)のとき登録ページ、True(有効)のときマイページ -->
            {% if object.active %}
              <a href="{% url 'visit:mypage' %}"
                class="btn">登録済みの面会詳細ページ</a>
            {% else %}
              <a href="{% url 'visit:regist_visit' %}"
                class="btn">面会情報を事前登録する</a>
            {% endif %}
            
            <a href="{% url 'accounts:logout' %}"
               class="btn">ログアウト</a>
          {% else %}
            <!-- ログイン状態ではない場合のボタン -->
            <a href="{% url 'accounts:signup' %}"
               class="btn">会員登録はこちら</a>
            <a href="{% url 'accounts:login' %}"
               class="btn">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
</section>